from threading import *

print(current_thread().getName())       #using getName() method return default name generated by python
current_thread().setName("ThroughOut Technology")  #set user defined name of thread by set Name
print(current_thread().getName())
print(current_thread().name)  